dubbo:

  application:
    name: mail-service
    qos-enable: true
    qos-port: 33332
    qos-accept-foreign-ip: false
  registry:
    protocol: zookeeper
    address: 106.13.197.193:2181
  protocol:
    port: 28811
  provider:
    timeout: 20000

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/v17?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: abc

server:
  port: 9091

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1358724404@qq.com
    password: eumlgekbdwomigfe
  rabbitmq:
    host: 106.13.197.193
    port: 5672
    username: root
    password: 517310
    virtual-host: /fuhan
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 106.13.197.193
    port: 6379
    password: 517310
  datasource:
    url: jdbc:mysql://localhost:3306/v17?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: StuBt1qH9CzJNLjnJocrY/jlgyzVpCOU6mYD+njEXMZYNZBdxpk6j65b7swJJQ9slVIkOrLuospnBtfjJmxz1Q==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJS/GIeCQadXEVsB55tfzt8N2lee5G98zgcQ47C0GGWMoIIXLxS2C3APu+xwAmoRZGzjBblMevaFl+Dc/PBHzB8CAwEAAQ==


mail:
  fromAddr: 1358724404@qq.com
