spring:
  redis:
    host: 106.13.197.193
    port: 6379
    password: 517310
  datasource:
    url: jdbc:mysql://localhost:3306/v17?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: StuBt1qH9CzJNLjnJocrY/jlgyzVpCOU6mYD+njEXMZYNZBdxpk6j65b7swJJQ9slVIkOrLuospnBtfjJmxz1Q==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJS/GIeCQadXEVsB55tfzt8N2lee5G98zgcQ47C0GGWMoIIXLxS2C3APu+xwAmoRZGzjBblMevaFl+Dc/PBHzB8CAwEAAQ==
dubbo:
  application:
    name: user-service
    qos-enable: true
    qos-port: 33336
    qos-accept-foreign-ip: false
  registry:
    protocol: zookeeper
    address: 106.13.197.193:2181
  protocol:
    port: 28815
server:
  port: 9095